# Generated by Django 4.2.3 on 2023-07-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_application_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='first_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='second_validation',
            field=models.BooleanField(default=False),
        ),
    ]
